id: I4F8CC4A4
ocr_import_info:
  timestamp: '2023-06-23T16:52:23.968929+00:00'
  batch_id: batch-5ca7
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-23 16:54:42.314552+00:00
last_modified: 2023-06-23 16:54:42.314559+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN1720
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN1720
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྐྱེ་བོ་གསོ་ཐིགས།
  languages:
  - bo
  author: སློབ་དཔོན་ཀླུ་སྒྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.9750518532682458
  ocr_word_median_confidence_index: 0.9992080249999999
bases:
  I3CN1722:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN1722
      total_pages: 14
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN1722.txt
    statistics:
      ocr_word_median_confidence_index: 0.9992080249999999
      ocr_word_mean_confidence_index: 0.9750518532682458
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
